import React, { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookUser, Search, UserPlus, Send, Trash2, X, Ticket } from "lucide-react";
import toast from "react-hot-toast";
import { supabase } from "../lib/supabase";
import { useTable } from "../lib/useData";
import { formatDate } from "../lib/helpers";
import { Button, Input, Label, Badge } from "./ui";

export default function StorePhonebook({ storeId, members, codes, refetchCodes }) {
  const { data: phonebook = [], refetch: refetchPhonebook } = useTable("store_phonebook", {
    filter: { store_member_id: storeId },
    order: "-created_at",
  });

  const [memberSearch, setMemberSearch] = useState("");
  const [phonebookSearch, setPhonebookSearch] = useState("");
  const [sendTarget, setSendTarget] = useState(null); // username being sent a code
  const [busy, setBusy] = useState(false);

  const approvedMembers = useMemo(
    () => members.filter(m => m.status === "approved" && m.role === "member"),
    [members]
  );

  const phonebookUsernames = useMemo(
    () => new Set(phonebook.map(p => p.username)),
    [phonebook]
  );

  // Members matching the search that are NOT yet in the phonebook
  const searchResults = useMemo(() => {
    const q = memberSearch.trim().toLowerCase();
    if (!q) return [];
    return approvedMembers
      .filter(m => m.username.toLowerCase().includes(q) && !phonebookUsernames.has(m.username))
      .slice(0, 8);
  }, [memberSearch, approvedMembers, phonebookUsernames]);

  // Phonebook entries filtered by the phonebook search box
  const filteredPhonebook = useMemo(() => {
    const q = phonebookSearch.trim().toLowerCase();
    if (!q) return phonebook;
    return phonebook.filter(p => p.username.toLowerCase().includes(q));
  }, [phonebook, phonebookSearch]);

  // Available codes: generated by this store, not used, not yet assigned
  const availableCodes = useMemo(
    () => codes.filter(c => c.generated_by_store_id === storeId && !c.is_used && !c.assigned_username),
    [codes, storeId]
  );

  async function addToPhonebook(member) {
    const { error } = await supabase.from("store_phonebook").insert({
      store_member_id: storeId,
      username: member.username,
      member_id: member.id,
    });
    if (error) {
      if (error.code === "23505") toast.error("Already in your phonebook");
      else toast.error("Failed to add");
      return;
    }
    toast.success(`@${member.username} added to phonebook`);
    setMemberSearch("");
    refetchPhonebook();
  }

  async function removeFromPhonebook(entry) {
    const { error } = await supabase.from("store_phonebook").delete().eq("id", entry.id);
    if (error) { toast.error("Failed to remove"); return; }
    toast.success(`@${entry.username} removed`);
    refetchPhonebook();
  }

  async function sendCode(codeId, username) {
    setBusy(true);
    try {
      const { error } = await supabase
        .from("maintenance_codes")
        .update({ assigned_username: username })
        .eq("id", codeId)
        .eq("is_used", false);
      if (error) throw error;
      toast.success(`Code sent to @${username}`);
      setSendTarget(null);
      refetchCodes();
    } catch {
      toast.error("Failed to send code");
    }
    setBusy(false);
  }

  return (
    <div className="bg-white rounded-3xl shadow-lg border border-gray-100 overflow-hidden mb-6">
      <div className="p-6 border-b border-gray-100">
        <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
          <BookUser className="w-5 h-5 text-teal-500" /> Phonebook
        </h2>
        <p className="text-sm text-gray-500 mt-1">Add usernames and send available codes directly to them.</p>
      </div>

      <div className="p-6 space-y-5">
        {/* Add to phonebook */}
        <div>
          <Label>Add a username to your phonebook</Label>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              value={memberSearch}
              onChange={e => setMemberSearch(e.target.value)}
              placeholder="Search approved members by username…"
              className="pl-10"
            />
          </div>
          <AnimatePresence>
            {searchResults.length > 0 && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="mt-2 border border-gray-100 rounded-xl divide-y divide-gray-50 overflow-hidden"
              >
                {searchResults.map(m => (
                  <div key={m.id} className="flex items-center justify-between px-4 py-2.5 hover:bg-gray-50">
                    <div>
                      <p className="text-sm font-medium text-gray-900">@{m.username}</p>
                      {m.full_name && <p className="text-xs text-gray-400">{m.full_name}</p>}
                    </div>
                    <Button size="sm" variant="outline" onClick={() => addToPhonebook(m)}>
                      <UserPlus className="w-3.5 h-3.5" /> Add
                    </Button>
                  </div>
                ))}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Phonebook list */}
        <div>
          <Label>My Phonebook ({phonebook.length})</Label>
          <div className="relative mb-3">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              value={phonebookSearch}
              onChange={e => setPhonebookSearch(e.target.value)}
              placeholder="Search your phonebook…"
              className="pl-10"
            />
          </div>

          {filteredPhonebook.length === 0 ? (
            <p className="text-center py-8 text-gray-400 text-sm">
              {phonebook.length === 0 ? "Your phonebook is empty. Search above to add usernames." : "No matching entries."}
            </p>
          ) : (
            <div className="space-y-2">
              {filteredPhonebook.map(entry => (
                <div key={entry.id} className="flex items-center justify-between bg-gray-50 rounded-xl px-4 py-3">
                  <div className="flex items-center gap-3">
                    <div className="w-9 h-9 bg-gradient-to-br from-teal-400 to-emerald-500 rounded-full flex items-center justify-center text-white font-bold text-sm">
                      {entry.username.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-900">@{entry.username}</p>
                      <p className="text-xs text-gray-400">Added {formatDate(entry.created_at, "MMM d, yyyy")}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      className="bg-gradient-to-r from-teal-500 to-emerald-600 text-white"
                      onClick={() => setSendTarget(entry.username)}
                      disabled={availableCodes.length === 0}
                    >
                      <Send className="w-3.5 h-3.5" /> Send Code
                    </Button>
                    <button
                      onClick={() => removeFromPhonebook(entry)}
                      className="p-2 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 transition-colors"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
          {availableCodes.length === 0 && phonebook.length > 0 && (
            <p className="text-xs text-amber-600 mt-2">No available codes to send. Generate codes first.</p>
          )}
        </div>
      </div>

      {/* Send-code modal */}
      <AnimatePresence>
        {sendTarget && (
          <>
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              onClick={() => setSendTarget(null)}
              className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
            >
              <motion.div
                initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
                onClick={e => e.stopPropagation()}
                className="bg-white rounded-3xl shadow-2xl w-full max-w-md overflow-hidden"
              >
                <div className="flex items-center justify-between p-5 border-b border-gray-100">
                  <h3 className="font-bold text-gray-900 flex items-center gap-2">
                    <Ticket className="w-5 h-5 text-teal-500" /> Send Code to @{sendTarget}
                  </h3>
                  <button onClick={() => setSendTarget(null)} className="p-1.5 rounded-lg hover:bg-gray-100">
                    <X className="w-5 h-5 text-gray-400" />
                  </button>
                </div>
                <div className="p-5 max-h-80 overflow-y-auto">
                  {availableCodes.length === 0 ? (
                    <p className="text-center text-gray-400 py-6">No available codes. Generate codes first.</p>
                  ) : (
                    <div className="space-y-2">
                      {availableCodes.map(c => (
                        <div key={c.id} className="flex items-center justify-between bg-gray-50 rounded-xl px-4 py-3">
                          <span className="font-mono font-bold text-sm text-gray-900">{c.code}</span>
                          <Button
                            size="sm"
                            className="bg-gradient-to-r from-teal-500 to-emerald-600 text-white"
                            disabled={busy}
                            onClick={() => sendCode(c.id, sendTarget)}
                          >
                            <Send className="w-3.5 h-3.5" /> Send
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
