import React, { useState, useMemo, useEffect } from "react";
import { Search, Copy, Clock, Ticket } from "lucide-react";
import toast from "react-hot-toast";
import { maintenanceStatus, formatTime, formatDate } from "../lib/helpers";
import { redeemCodeForMember } from "../lib/redeem";
import { Button, Input } from "./ui";

const REDEEM_UNLOCK_THRESHOLD = 0; // redeem enabled only when 12h maintenance cycle is fully expired

export default function StoreAvailableCodes({ storeId, members, codes, refetchCodes, refetchHistory, onRedeemDone }) {
  const [search, setSearch] = useState("");
  const [busyId, setBusyId] = useState(null);
  const [now, setNow] = useState(Date.now());

  // Tick every second for countdown timers
  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  // Available codes: generated by this store, assigned to a username, not yet used
  const availableCodes = useMemo(
    () => codes
      .filter(c => c.generated_by_store_id === storeId && c.assigned_username && !c.is_used)
      .sort((a, b) => new Date(b.created_at) - new Date(a.created_at)),
    [codes, storeId]
  );

  // Filter by username search
  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return availableCodes;
    return availableCodes.filter(c => c.assigned_username.toLowerCase().includes(q));
  }, [availableCodes, search]);

  async function handleRedeem(code) {
    const member = members.find(m => m.username === code.assigned_username);
    if (!member) { toast.error("Member not found"); return; }

    const status = maintenanceStatus(member, codes);
    if (status.isGreen && status.secondsLeft > REDEEM_UNLOCK_THRESHOLD) {
      toast.error(`Redeem unlocks in ${formatTime(status.secondsLeft - REDEEM_UNLOCK_THRESHOLD)} when the 12-hour cycle ends.`);
      return;
    }

    setBusyId(code.id);
    try {
      const result = await redeemCodeForMember(code, member, members, codes);
      toast.success(result.message);
      refetchCodes();
      refetchHistory();
      if (onRedeemDone) onRedeemDone();
    } catch (err) {
      toast.error(err.message || "Failed to redeem code");
    }
    setBusyId(null);
  }

  function copyCode(code) {
    navigator.clipboard.writeText(code);
    toast.success("Code copied!");
  }

  return (
    <div className="bg-white rounded-3xl shadow-lg border border-gray-100 overflow-hidden mb-6">
      <div className="p-6 border-b border-gray-100">
        <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
          <Ticket className="w-5 h-5 text-teal-500" /> Available Codes
        </h2>
        <p className="text-sm text-gray-500 mt-1">Codes designated to members. Redeem on their behalf when the timer unlocks.</p>
      </div>

      <div className="p-6">
        {/* Search by username */}
        <div className="relative mb-4">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <Input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search by username…"
            className="pl-10"
          />
        </div>

        {filtered.length === 0 ? (
          <p className="text-center py-8 text-gray-400 text-sm">
            {availableCodes.length === 0
              ? "No available codes. Generate codes with a designated username to see them here."
              : "No matching usernames."}
          </p>
        ) : (
          <div className="divide-y divide-gray-50 max-h-[640px] overflow-y-auto">
            {filtered.map(c => {
              const member = members.find(m => m.username === c.assigned_username);
              const status = member ? maintenanceStatus(member, codes) : null;
              const isLocked = status?.isGreen && status.secondsLeft > REDEEM_UNLOCK_THRESHOLD;
              const unlockSeconds = isLocked ? status.secondsLeft - REDEEM_UNLOCK_THRESHOLD : 0;

              return (
                <div key={c.id} className="flex items-center justify-between px-1 py-4">
                  <div className="min-w-0 flex-1">
                    <p className="font-mono font-bold text-gray-900 text-base">{c.code}</p>
                    <p className="text-xs text-gray-400 mt-0.5">
                      Received {formatDate(c.created_at, "MMM d, yyyy h:mm a")}
                    </p>
                    {isLocked && (
                      <p className="text-xs font-semibold text-orange-600 mt-1 flex items-center gap-1">
                        <Clock className="w-3 h-3" /> Unlocks in {formatTime(unlockSeconds)}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2 flex-shrink-0 ml-4">
                    <Button
                      size="sm"
                      variant="outline"
                      className="bg-gray-50 border-gray-200 text-gray-600"
                      onClick={() => copyCode(c.code)}
                    >
                      <Copy className="w-3.5 h-3.5" /> Copy
                    </Button>
                    <Button
                      size="sm"
                      disabled={isLocked || busyId === c.id}
                      className={isLocked
                        ? "bg-gray-300 text-gray-500 cursor-not-allowed"
                        : "bg-gray-600 hover:bg-gray-700 text-white"}
                      onClick={() => handleRedeem(c)}
                    >
                      {busyId === c.id ? "Redeeming…" : "Redeem"}
                    </Button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
